name: stomp_dart_client
homepage: https://github.com/blackhorse-one/stomp_dart
version: 3.0.1
description: Dart STOMP client for easy messaging interoperability. Build with flutter in mind, but should work for every dart application.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  web_socket: ^1.0.1

dev_dependencies:
  test: ^1.25.8
  lints: ^6.0.0
  stream_channel: ^2.1.2
